"""add recording feilds for rrweb and projectid

Revision ID: 1ef682eaa6cd
Revises: c495234c2fb8
Create Date: 2025-03-16 01:12:44.837224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef682eaa6cd'
down_revision: Union[str, None] = 'c495234c2fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('project_id', sa.String(length=50), nullable=False))
    op.add_column('recording', sa.Column('session_id', sa.String(length=250), nullable=True))
    op.add_column('recording', sa.Column('client_id', sa.String(length=250), nullable=True))
    op.add_column('recording', sa.Column('client_data', sa.JSON(), nullable=True))
    op.add_column('recording', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.alter_column('recording', 'file_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('recording', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recording', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'recording', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recording', type_='unique')
    op.alter_column('recording', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('recording', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recording', 'file_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('recording', 'meta_data')
    op.drop_column('recording', 'client_data')
    op.drop_column('recording', 'client_id')
    op.drop_column('recording', 'session_id')
    op.drop_column('org', 'project_id')
    # ### end Alembic commands ###
