"""rrweb session analysis


Revision ID: 867f634cc0e1
Revises: 54475c8b4900
Create Date: 2026-02-11 21:24:57.087085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867f634cc0e1'
down_revision: Union[str, None] = '54475c8b4900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('issue', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('issue', sa.Column('target', sa.String(length=500), nullable=True))
    op.add_column('issue', sa.Column('confidence', sa.String(length=20), nullable=True))
    op.add_column('issue_recording', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('issue_recording', sa.Column('target', sa.String(length=500), nullable=True))
    op.add_column('issue_recording', sa.Column('confidence', sa.String(length=20), nullable=True))
    op.add_column('issue_recording', sa.Column('timestamp', sa.String(length=8), nullable=True))
    op.add_column('issue_recording', sa.Column('frequency', sa.Integer(), nullable=True))
    op.add_column('issue_recording', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('issue_recording', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('issue_recording', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('issue_recording', sa.Column('reproduction_steps', sa.Text(), nullable=True))
    op.add_column('issue_recording', sa.Column('analysis_tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_recording', 'analysis_tier')
    op.drop_column('issue_recording', 'reproduction_steps')
    op.drop_column('issue_recording', 'root_cause')
    op.drop_column('issue_recording', 'category')
    op.drop_column('issue_recording', 'severity')
    op.drop_column('issue_recording', 'frequency')
    op.drop_column('issue_recording', 'timestamp')
    op.drop_column('issue_recording', 'confidence')
    op.drop_column('issue_recording', 'target')
    op.drop_column('issue_recording', 'type')
    op.drop_column('issue', 'confidence')
    op.drop_column('issue', 'target')
    op.drop_column('issue', 'type')
    op.drop_column('issue', 'root_cause')
    # ### end Alembic commands ###
