"""Added recording analysis status

Revision ID: f0dfdd8a53ca
Revises: fdbc9dbbc03f
Create Date: 2025-01-24 11:42:47.699973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dfdd8a53ca'
down_revision: Union[str, None] = 'fdbc9dbbc03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording', sa.Column('analysis_status', sa.String(length=50), nullable=False, server_default='PENDING'))
    op.add_column('recording', sa.Column('analysis_error', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording', 'analysis_error')
    op.drop_column('recording', 'analysis_status')
    # ### end Alembic commands ###
