"""enhanced recording model

Revision ID: 013d345509ec
Revises: f0dfdd8a53ca
Create Date: 2025-02-04 18:06:15.877105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013d345509ec'
down_revision: Union[str, None] = 'f0dfdd8a53ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording', sa.Column('file_duration', sa.Float(), nullable=True))
    op.add_column('recording', sa.Column('analysis_progress', sa.Integer(), server_default='0', nullable=False))
    op.add_column('recording', sa.Column('short_title', sa.Text(), nullable=True))
    op.add_column('recording', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('recording', sa.Column('tags', sa.String(length=250), nullable=True))
    op.alter_column('recording', 'analysis_error',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recording', 'analysis_error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.drop_column('recording', 'tags')
    op.drop_column('recording', 'summary')
    op.drop_column('recording', 'short_title')
    op.drop_column('recording', 'analysis_progress')
    op.drop_column('recording', 'file_duration')
    # ### end Alembic commands ###
