"""adjusted recording summary length

Revision ID: 5d4e636d19f2
Revises: 6d6b902d91ad
Create Date: 2025-02-04 13:39:20.623353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4e636d19f2'
down_revision: Union[str, None] = '6d6b902d91ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
