"""adjusted recording_interval

Revision ID: 65bbd7e11830
Revises: f1d1630713d8
Create Date: 2025-01-23 17:34:01.144720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bbd7e11830'
down_revision: Union[str, None] = 'f1d1630713d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording_interval', sa.Column('description', sa.String(), nullable=False))
    op.add_column('recording_interval', sa.Column('short_title', sa.String(), nullable=False))
    op.add_column('recording_interval', sa.Column('timestamp_descriptions', sa.JSON(), nullable=False))
    op.drop_column('recording_interval', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording_interval', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('recording_interval', 'timestamp_descriptions')
    op.drop_column('recording_interval', 'short_title')
    op.drop_column('recording_interval', 'description')
    # ### end Alembic commands ###
