"""adjusted recording model

Revision ID: 6d6b902d91ad
Revises: f0dfdd8a53ca
Create Date: 2025-02-04 11:22:54.418652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6b902d91ad'
down_revision: Union[str, None] = 'f0dfdd8a53ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording', sa.Column('analysis_progress', sa.Integer(), server_default='0', nullable=False))
    op.add_column('recording', sa.Column('short_title', sa.String(length=250), nullable=True))
    op.add_column('recording', sa.Column('summary', sa.String(length=250), nullable=True))
    op.add_column('recording', sa.Column('tags', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording', 'tags')
    op.drop_column('recording', 'summary')
    op.drop_column('recording', 'short_title')
    op.drop_column('recording', 'analysis_progress')
    # ### end Alembic commands ###
