"""added file_duration

Revision ID: acae21633b0c
Revises: 16250a6b7f47
Create Date: 2025-02-04 17:31:01.100664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acae21633b0c'
down_revision: Union[str, None] = '16250a6b7f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording', sa.Column('file_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording', 'file_duration')
    # ### end Alembic commands ###
